# Generated by Django 5.2.5 on 2025-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Document'), ('social_media', 'Social Media'), ('website', 'Personal Website')], default='pdf', max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('vector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type'], name='assistant_p_source__c5c926_idx'), models.Index(fields=['created_at'], name='assistant_p_created_9ae4db_idx')],
            },
        ),
    ]
