# Generated by Django 5.2.5 on 2025-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_portfolioitem_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
